### ISSUE TITLE
EStyleSheet.create returned number instead of object

### ISSUE THREAD

**Issue by michael-lianto** [vitalets/react-native-extended-stylesheet#36] opened 2017-04-05 14:40 UTC
Hi, thanks for this great library for styling,

I've used the old version of EStyleSheet, and it works :)
but  now i'm in a new project with RN 0.41 and the EStyleSheet 0.3.2,
i got plenty warning that invalid property type of style, it

here's where i declare the build in my app.js:
```
'use` strict';

import React,{ Component } from 'react';
import { StyleSheet, Dimensions, Image, Alert, BackAndroid } from 'react-native';
import { Container, Content, Text, View } from 'native-base';
import EStyleSheet from 'react-native-extended-stylesheet';
import AppNavigator from './AppNavigator';

let {height, width} = Dimensions.get('window');
let styles = StyleSheet.create({
  container: {
    flex: 1,
    width: null,
    height: null,
  },
  box: {
    padding: 10,
    backgroundColor: 'transparent',
    flex: 1,
    height: height-70
  },
  space: {
    marginTop: 10,
    marginBottom: 10,
    justifyContent: 'center'
  },
  modal: {
    justifyContent: 'center',
    alignItems: 'center'
  },
  modal1: {
    height: 300

  },
  modal2: {
    height: height-78,
    position: 'relative',
    justifyContent: 'center',
  },
});

class App extends Component {

  constructor(props) {
    super(props);
    
  }


  render() {
     //some render
  }
}

EStyleSheet.build({
  rem: width > 500 ? 2 : 1,
  $scale: width > 500 ? 1 : 1
});

export default App
```

and my class
```
import React, { Component } from 'react';
import { Image, Platform, StyleSheet } from 'react-native';
import { connect } from 'react-redux';
import { Actions } from 'react-native-router-flux';
import { Container, Content, Text, Item, Input, Button, Icon, View, Form, Header } from 'native-base';

import styles from './styles';

const backgroundImage = require('../../../../images/login.png');

class Login extends Component {

  constructor(props) {
    super(props);
    this.state = {
      email: '',
      password: '',
      scroll: false,
    };
  }

  render() {
    return (
      <Container>

        <Content scrollEnabled={true} bounces={false}>
          <Image source={backgroundImage} style={styles.container}>
            <View style={styles.bg}>
              <Button style={styles.buttonLoginFacebook} onPress={() => Actions.main()}>
                <Text style={styles.buttonTextLogin}>
                  Login with facebook
                </Text>
              </Button>
              <Button style={styles.buttonRegisterFacebook} onPress={() => Actions.signUp()}>
                <Text style={styles.buttonTextLogin}>
                  Register with facebook
                </Text>
              </Button>
            </View>
          </Image>
        </Content>
      </Container>
    );
  }
}

export default connect()(Login);`
```
and finally, my style.js:
```
'use strict';
const React = require('react-native');
import EStyleSheet from 'react-native-extended-stylesheet';
const { StyleSheet, Dimensions, Platform } = React;

const deviceHeight = Dimensions.get('window').height;

module.exports = EStyleSheet.create({
  $outline: 1,
  container: {
    flex: 1,
    width: null,
    height: '100%',
    resizeMode: 'cover',
    alignItems: 'center',
  },
  buttonTextLogin: {
    color: '#000',
    width: '90%',
    textAlign: 'center'
  },
  buttonRegisterFacebook: {
    backgroundColor: '#cf4965',
    width: '90%'
  },
  shadow: {
    flex: 1,
    marginTop: (deviceHeight < 600) ? -40 : -10,
    width: null,
    height: null,
    backgroundColor: 'transparent',
  },
  bg: {
    backgroundColor: 'rgba(255,0,0,0)',
  },
  buttonLoginFacebook: {
    backgroundColor: '#454190',
    width: '90%'
  },

});
```

But the style doesn't make any effect on my layout, and i keep getting lots of warning,
`Warning: Failed prop type: Invalid prop 'style' of type 'number' supplied to 'Styled(Text)', expected 'object'
Warning: Failed prop type: Invalid prop 'style' of type 'number' supplied to 'Styled(Button)', expected 'object'
Warning: Failed prop type: Invalid prop 'style' of type 'number' supplied to 'Styled(Content)', expected 'object'
Warning: Failed prop type: Invalid prop 'style' of type 'number' supplied to 'Styled(Button)', expected 'object'`

Fyi, i did  make sure the path is correct, so it's not import problem.
and my package.json
```
{
  "name": "xxx",
  "version": "6.0.0",
  "private": true,
  "scripts": {
    "postinstall": "remotedev-debugger",
    "start": "node_modules/react-native/packager/packager.sh",
    "eslint": "eslint"
  },
  "dependencies": {
    "@remobile/react-native-cordova": "^1.1.1",
    "@remobile/react-native-file-transfer": "^1.0.7",
    "bugsnag-react-native": "^2.2.0",
    "color": "^0.11.3",
    "lodash": "^4.13.1",
    "moment": "^2.13.0",
    "native-base": "2.1.0-rc.2",
    "react": "15.4.2",
    "react-native": "0.41.0",
    "react-native-button": "^1.6.0",
    "react-native-code-push": "^1.17.0-beta",
    "react-native-extended-stylesheet": "^0.3.2",
    "react-native-fcm": "^6.2.0",
    "react-native-gifted-messenger": "^0.1.4",
    "react-native-gifted-spinner": "0.0.5",
    "react-native-image-picker": "^0.26.2",
    "react-native-loading-spinner-overlay": "^0.4.2",
    "react-native-modalbox": "^1.3.7",
    "react-native-navigation-redux-helpers": "^0.5.0",
    "react-native-router-flux": "^3.38.0",
    "react-native-scrollable-tab-view": "^0.7.2",
    "react-native-storage": "^0.1.5",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-persist": "^3.2.2",
    "redux-thunk": "^2.1.0",
    "remote-redux-devtools": "^0.3.3",
    "remote-redux-devtools-on-debugger": "^0.4.6"
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "babel-eslint": "^6.1.2",
    "eslint": "^3.5.0",
    "eslint-config-airbnb": "^11.1.0",
    "eslint-plugin-import": "^1.14.0",
    "eslint-plugin-jsx-a11y": "^2.2.1",
    "eslint-plugin-react": "^6.2.0",
    "eslint-plugin-react-native": "^2.0.0",
    "mocha": "^2.5.3",
    "babel-jest": "19.0.0",
    "jest": "19.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

*updated:

```
render() {
    console.log(StyleSheet.flatten(styles));
    return (
      <Container>
        <Content scrollEnabled={true} bounces={false}>
          <Image source={backgroundImage} style={StyleSheet.flatten(styles.container)}>
            <View style={StyleSheet.flatten(styles.bg)}>
              <Button style={StyleSheet.flatten(styles.buttonLoginFacebook)} onPress={() => Actions.main()}>
                <Text style={StyleSheet.flatten(styles.buttonTextLogin)}>
                  Login with facebook
                </Text>
              </Button>
              <Button style={StyleSheet.flatten(styles.buttonRegisterFacebook)} onPress={() => Actions.signUp()}>
                <Text style={StyleSheet.flatten(styles.buttonTextLogin)}>
                  Register with facebook
                </Text>
              </Button>
            </View>
          </Image>
        </Content>
      </Container>
    );
  }
```
if i use the flatten method in react-native Stylesheet, it worked, it rendered the outline correctly (for $outline: 1), everything works, but it's kinda absurd to write Stylesheet.flatten() everytime, right?

**Comment by vitalets** [comment] 2017-04-07 16:07
hi @michael-lianto ! Is it on IOS, Android or both?

**Comment by michael-lianto** [comment] 2017-04-09 16:39
hi @vitalets sorry the late reply,
i've only tried for android, dunno about the iOS though.

thanks for replying :)

**Comment by vitalets** [comment] 2017-04-10 13:39
Maybe it is because there is `module.exports` instead of `export default`.
Please try to change this:
```js
module.exports = EStyleSheet.create({
```
to
```js
export default EStyleSheet.create({
```

**Comment by vitalets** [comment] 2017-06-05 10:45
Closing as outdated.

**Comment by klujanrosas** [comment] 2017-08-17 14:58
I just ran into the same problem:
```
// styles.js file
...
export default EStyleSheet.create({
     container: {
         backgroundColor: 'red',
     }
})
```

I got a number instead of an object when trying to pass the style object as a prop to another component like this: 

```
<FAIcon customStyle={styles.container} {...otherProps} />
```

When I console log styles.container it outputs a number. (Pic is of alert)
![screenshot_4](https://user-images.githubusercontent.com/4474353/29418630-8988d240-8332-11e7-8974-2eef046a0385.png)

**Comment by vitalets** [comment] 2017-08-28 06:59
will have a look.

**Comment by vitalets** [comment] 2017-08-29 17:49
As I re-checked - this is intended behavior for React Native styles. They operate IDs instead of objects for performance reasons. Please see details here: https://facebook.github.io/react-native/docs/stylesheet.html#stylesheet

To get back style from the ID you can use `EStyleSheet.flatten(styles.container)`.

**Closed by vitalets** 2017-08-29 17:49 UTC

**Comment by klujanrosas** [comment] 2017-08-29 17:52
I saw that one could also access the actual style by prepending a '_' to the style name, like:
styles._container
Thanks for clarification!

**Comment by vitalets** [comment] 2017-08-30 07:30
@klujanrosas yes, exactly. It was done before `.flatten` appeared.
